# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class UsbipdMac < Formula
  desc "Macos implementation of the usb/ip protocol"
  homepage "https://github.com/beriberikix/usbipd-mac"
  url "https://github.com/beriberikix/usbipd-mac/archive/refs/tags/v0.0.17.tar.gz"
  version "0.0.17"
  sha256 "343b939bdefc11538265aa7d4bfb3977880929d41b7e6353368d287b6c3513e8"

  on_macos do
  end

  def install
    bin.install "usbipd"
  end

  test do
    assert_match "usbipd", shell_output("#{bin}/usbipd --version")
  end
end
