# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class UsbipdMac < Formula
  desc "Macos implementation of the usb/ip protocol"
  homepage "https://github.com/beriberikix/usbipd-mac"
  url "https://github.com/beriberikix/usbipd-mac/archive/refs/tags/v0.1.19.tar.gz"
  version "0.1.19"
  sha256 "26e97fcbfe041803d12cf06b8a7bfadef84ddc7be5fbf3ec35a4d8553376bac8"

  on_macos do
  end

  def install
    bin.install "usbipd"
  end

  test do
    assert_match "usbipd", shell_output("#{bin}/usbipd --version")
  end
end
