name: Formula Update

on:
  repository_dispatch:
    types: [release-published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v0.0.12)'
        required: true
        type: string

jobs:
  update:
    name: Update Formula
    runs-on: ubuntu-latest
    steps:
      - name: 🔍 Extract Release Information
        id: info
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
            SOURCE_REPO="beriberikix/usbipd-mac"
          else
            VERSION="${{ github.event.client_payload.release.tag_name }}"
            SOURCE_REPO="${{ github.event.client_payload.repository }}"
          fi
          
          echo "📡 Webhook update for $VERSION from $SOURCE_REPO"
          
          if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?$ ]]; then
            echo "::error::Invalid version format: $VERSION"
            exit 1
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "source-repo=$SOURCE_REPO" >> $GITHUB_OUTPUT

      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔧 Setup
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: 📥 Download Metadata
        run: |
          VERSION="${{ steps.info.outputs.version }}"
          SOURCE_REPO="${{ steps.info.outputs.source-repo }}"
          URL="https://github.com/$SOURCE_REPO/releases/download/$VERSION/homebrew-metadata.json"
          
          echo "📥 Downloading: $URL"
          curl -L -f -s "$URL" -o metadata.json
          
          if ! jq empty metadata.json; then
            echo "::error::Invalid JSON metadata"
            exit 1
          fi

      - name: 🍺 Update Formula
        run: |
          VERSION="${{ steps.info.outputs.version }}"
          ARCHIVE_URL=$(jq -r '.metadata.archive_url' metadata.json)
          SHA256=$(jq -r '.metadata.sha256' metadata.json)
          
          echo "🍺 Updating to $VERSION"
          echo "   URL: $ARCHIVE_URL"
          echo "   SHA256: $SHA256"
          
          FORMULA="Formula/usbipd-mac.rb"
          cp "$FORMULA" "$FORMULA.backup"
          
          sed -i "s|archive/v[0-9][0-9.]*\\.tar\\.gz|archive/$VERSION.tar.gz|g" "$FORMULA"
          sed -i "s|version \"v[0-9][0-9.]*\"|version \"$VERSION\"|g" "$FORMULA"
          sed -i "s|sha256 \"[a-f0-9]\\{64\\}\"|sha256 \"$SHA256\"|g" "$FORMULA"

      - name: 🔍 Validate
        run: |
          VERSION="${{ steps.info.outputs.version }}"
          SHA256=$(jq -r '.metadata.sha256' metadata.json)
          
          ruby -c Formula/usbipd-mac.rb
          
          if ! grep -q "version \"$VERSION\"" Formula/usbipd-mac.rb; then
            echo "::error::Version not updated correctly"
            exit 1
          fi
          
          if ! grep -q "sha256 \"$SHA256\"" Formula/usbipd-mac.rb; then
            echo "::error::SHA256 not updated correctly"
            exit 1
          fi
          
          echo "✅ Formula validation passed"

      - name: 📄 Commit and Push
        run: |
          VERSION="${{ steps.info.outputs.version }}"
          SOURCE_REPO="${{ steps.info.outputs.source-repo }}"
          
          if git diff --quiet Formula/usbipd-mac.rb; then
            echo "⚠️ No changes to commit"
          else
            git add Formula/usbipd-mac.rb
            git commit -m "feat: update formula to $VERSION

Automated update triggered by release webhook from $SOURCE_REPO

🤖 Generated with [Claude Code](https://claude.ai/code)

Co-Authored-By: Claude <noreply@anthropic.com>"
            
            git push origin main
            echo "✅ Formula updated and pushed"
          fi

      - name: 🎉 Success
        run: |
          echo "🎉 Formula update completed successfully!"
          echo "📦 Version: ${{ steps.info.outputs.version }}"
          echo "🍺 Formula: beriberikix/usbipd-mac/usbipd-mac"
          echo ""
          echo "🔗 External Tap Integration Complete:"
          echo "   • ✅ Webhook delivery working"
          echo "   • ✅ Repository dispatch triggered"
          echo "   • ✅ Formula updated automatically"
          echo "   • ✅ End-to-end automation operational"